---
name: "Request a free subdomain"
about: "Request a free subdomain like example.estin.pro"
title: "[subdomain request] "
labels: ["subdomain-request"]
---

**Requested subdomain** (only letters, numbers, hyphen; no spaces) e.g. `bob`  

**Where should it point?** (optional) URL or GitHub Pages repo (e.g. https://username.github.io/myproject)  

**Short description / purpose**

I agree to the Terms of Service / Abuse policy: YES
